#!/bin/bash

file="${1}"

if [ -z "${file}" ]
then 
	echo "Add a C File name without the .c extension"
	exit 1
fi 

if [ ! -f "${file}.c" ]
then 
	echo "File does not exist!"
	exit 1
fi 


gcc -o "${file}" "${file}.c"

./"${file}"
